my_class:
  _target_ : hydra_instantiate.MyClass # _target_ is special
  name : hydra # name is the parameter to be passed in my class

optimizer:
  _target_ : torch.optim.Adam
  _partial_ : True
  lr : 0.01